<a href="https://colab.research.google.com/github/Viktoriia-kama/ML_hw4-hw16/blob/main/HW4%2B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [15]:
arr = np.array([1, 2, 3, 7, 5, 6, 7, 8, 9])
for i in range(len(arr)):
  if arr[i]%2 !=0:
    arr[i]=-1
arr


array([-1,  2, -1, -1, -1,  6, -1,  8, -1])

In [18]:
arr_1d = np.random.randint(0, 16, size=(8))
np.reshape(arr_1d, (2,-1))

array([[ 6,  9, 11, 15],
       [ 8,  1, 11,  8]])

In [24]:
a = np.random.randint(0, 11, size=(2,3))
b = np.random.randint(0, 11, size=(3,3))
print(a,b)

np.vstack((a, b))

[[5 6 5]
 [6 3 3]] [[ 6  4  2]
 [ 4 10  4]
 [ 5  3  0]]


array([[ 5,  6,  5],
       [ 6,  3,  3],
       [ 6,  4,  2],
       [ 4, 10,  4],
       [ 5,  3,  0]])

In [6]:
a = np.array([1, 2, 3])
np.concatenate((np.repeat(a,3), a, a, a))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [7]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

In [11]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)
np.argsort(a)[-5:]

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]


array([18,  7,  3, 10, 15])

In [17]:
а=np.array([1,2,3,np.nan,5,6,7,np.nan])
mask = ~np.isnan(a)
result = a[mask]
print(result)

[1. 2. 3. 5. 6. 7.]


In [18]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
np.linalg.norm(a-b)

6.708203932499369

In [21]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices = np.where(x == 1)[0]
indices[4]

8