In [1]:
import numpy as np

In [5]:
array = [i for i in range(1,11)]
print(array)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [6]:
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [12]:
array = np.random.randint(1, 11, size = (5, 5))
print(array)

[[ 2  7  3  4  8]
 [ 6  2  6 10  8]
 [ 5  1  7  8  6]
 [ 1  6  8  7  9]
 [ 6 10  8  2  9]]


In [10]:
array = np.random.rand(4, 4)
print(array)


[[0.57886481 0.21562108 0.44193659 0.7752043 ]
 [0.92281834 0.8376448  0.9165172  0.62339479]
 [0.9318826  0.93029556 0.66901053 0.84045175]
 [0.18412487 0.14458313 0.06365932 0.53667739]]


In [15]:
array1 = np.random.randint(1, 11, size = (5,))
array2 = np.random.randint(1, 11, size = (5,))
print (array1)
print (array2)
print(f"додавання {array1+array2}")
print(f"віднімання {array1/array2}")
print(f"множення {array1*array2}")

[ 4  7  5 10  3]
[4 4 4 6 4]
додавання [ 8 11  9 16  7]
віднімання [1.         1.75       1.25       1.66666667 0.75      ]
множення [16 28 20 60 12]


In [17]:
# Створіть два вектори розміром 7, заповніть довільними
# числами та знайдіть їх скалярний добуток.
array1 = np.random.randint(1, 100, size = (7,))
array2 = np.random.randint(1, 100, size = (7,))
print (array1)
print (array2)
print(f"скалярний добуток {np.dot(array1,array2)}")

[79 55 17  3 62 55 81]
[74 55 37 62  1 27 14]
скалярний добуток 12367


In [18]:
# Створіть дві матриці розміром 2x2 та 2x3, заповніть їх
# випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
array1 = np.random.randint(1, 11, size = (2,2))
array2 = np.random.randint(1, 11, size = (2,3))
print (array1)
print (array2)
print(f"множення матриць {np.dot(array1,array2)}")

[[4 5]
 [7 9]]
[[7 7 2]
 [4 9 9]]
множення матриць [[ 48  73  53]
 [ 85 130  95]]


In [19]:
# Створіть матрицю розміром 3x3, заповніть її випадковими
# цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
array1 = np.random.randint(1, 11, size = (3,3))
print (array1)
print(f"транспонована матриця {array1.T}")

[[10 10  6]
 [10  3  3]
 [ 7  4  3]]
транспонована матриця [[10 10  7]
 [10  3  4]
 [ 6  3  3]]


In [20]:
# Створіть матрицю розміром 4x4, заповніть її випадковими
# дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
array1 = np.random.rand(3,3)
print (array1)
print(f"транспонована матриця {array1.T}")

[[0.37484531 0.79070916 0.24206984]
 [0.47332899 0.24138902 0.42502695]
 [0.58143837 0.96440162 0.94548499]]
транспонована матриця [[0.37484531 0.47332899 0.58143837]
 [0.79070916 0.24138902 0.96440162]
 [0.24206984 0.42502695 0.94548499]]


In [22]:
# Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими
# цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
array1 = np.random.randint(1, 11, size = (3,4))
array2 = np.random.randint(1, 11, size = (4,))
print (array1)
print (array2)
print(f"множення матриці на вектор {np.dot(array1,array2)}")

[[5 6 1 5]
 [7 4 4 8]
 [4 9 4 6]]
[8 9 5 8]
множення матриці на вектор [139 176 181]


In [23]:
# Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими
# дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
array1 = np.random.rand(2,3)
array2 = np.random.rand(3,)
print (array1)
print (array2)
print(f"множення матриці на вектор {np.dot(array1,array2)}")

[[0.22922154 0.63886871 0.46691315]
 [0.74621408 0.17231642 0.96626301]]
[0.52874676 0.26994304 0.08975205]
множення матриці на вектор [0.33556472 0.52779798]


In [24]:
# Створіть дві матриці розміром 2x2, заповніть їх випадковими
# цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення
array1 = np.random.randint(1, 11, size = (2,2))
array2 = np.random.randint(1, 11, size = (2,2))
print (array1)
print (array2)
print(f"множення матриць поелементно {array1*array2}")

[[1 9]
 [4 3]]
[[3 8]
 [2 3]]
множення матриць поелементно [[ 3 72]
 [ 8  9]]


In [29]:
array1 = np.random.rand(2,2)
array2 = np.random.rand(2,2)
print (array1)
print (array2)
print(f"добуток матриць {array1*array2}")

[[0.50999543 0.93167438]
 [0.81490531 0.5684411 ]]
[[0.2259572  0.19768952]
 [0.89962434 0.84279209]]
добуток матриць [[0.11523714 0.18418226]
 [0.73310865 0.47907766]]


In [27]:
# Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в
# діапазоні від 1 до 100 та знайдіть суму елементів матриці.
array = np.random.randint(1, 101, size = (5,5))
print (array)
print(f"сума елементів матриці {array.sum()}")

[[ 62  40  13  13  78]
 [  6  68 100  98  33]
 [ 47  57  75  61  11]
 [  8  27  37  53  54]
 [ 94   7  89  46  84]]
сума елементів матриці 1261


In [28]:
array1 = np.random.randint(1, 11, size = (4,4))
array2 = np.random.randint(1, 11, size = (4,4))
print (array1)
print (array2)
print(f"різниця матриць {array1-array2}")

[[ 3  8  2 10]
 [ 4  4  6  7]
 [ 9 10 10  7]
 [ 3  2  2  9]]
[[10 10 10  5]
 [ 4  1  1  6]
 [ 8  5 10  6]
 [ 7  4  9  3]]
різниця матриць [[-7 -2 -8  5]
 [ 0  3  5  1]
 [ 1  5  0  1]
 [-4 -2 -7  6]]


In [31]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами
# в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
array = np.random.rand(3,3)
print (array)
print(f"вектор-стовпчик, що містить суму елементів кожного рядка матриці {np.sum(array, axis=1)}")

[[0.20817145 0.73934563 0.08180567]
 [0.67474522 0.60195069 0.7861763 ]
 [0.44711166 0.24750693 0.52394406]]
вектор-стовпчик, що містить суму елементів кожного рядка матриці [1.02932275 2.06287221 1.21856265]


In [34]:
array = np.random.rand(3,3)
print (array)
print(f"матриця з квадратами цих чисел {np.square(array)}")

[[0.5575598  0.20642647 0.39536497]
 [0.18630087 0.49902947 0.52246082]
 [0.57327201 0.08648432 0.35106101]]
матриця з квадратами цих чисел [[0.31087293 0.04261189 0.15631346]
 [0.03470802 0.24903042 0.27296531]
 [0.3286408  0.00747954 0.12324383]]


In [35]:
array = np.random.randint(1, 51, size=4)
print(array)
print(f"Вектор з квадратними коренями: {np.sqrt(array)}")


[ 4  6  3 47]
Вектор з квадратними коренями: [2.         2.44948974 1.73205081 6.8556546 ]
